name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  test-deploy-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    env:
      SAP_CCV2_API_TOKEN: ${{ secrets.SAP_CCV2_API_TOKEN }}
      SAP_CCV2_SUB_CODE: ${{ secrets.SAP_CCV2_SUB_CODE }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          buildCode: '20240903.1'
          environmentCode: 'd1'
          databaseUpdateMode: 'UPDATE'
          deploymentMode: 'ROLLING_UPDATE'
          checkStatusInterval: 60000
          notify: true

      - name: Print Output
        id: output
        run: |
          echo "Deployment Code: ${{ steps.test-action.outputs.deploymentCode }}, Deployment Status: ${{ steps.test-action.outputs.deploymentStatus }}"